# ==============================================================================
# .zshrc — Main zsh configuration
# Managed by: https://github.com/k1v/dev-setup
# Edit here; symlinked from ~/
# ==============================================================================

# ------------------------------------------------------------------------------
# Powerlevel10k instant prompt — must stay at the very top
# ------------------------------------------------------------------------------
if [[ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]]; then
  source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
fi
typeset -g POWERLEVEL9K_INSTANT_PROMPT=quiet

# ------------------------------------------------------------------------------
# Oh My Zsh
# ------------------------------------------------------------------------------
export ZSH="$HOME/.oh-my-zsh"

ZSH_THEME="powerlevel10k/powerlevel10k"

# Plugins — order matters for some (autosuggestions before syntax-highlighting)
plugins=(
  git
  autojump
  zsh-autosuggestions
  zsh-syntax-highlighting
)

source "$ZSH/oh-my-zsh.sh"

# ------------------------------------------------------------------------------
# PATH additions
# ------------------------------------------------------------------------------
# Local bin (fd/bat shims live here)
export PATH="$HOME/.local/bin:$PATH"

# Prepend Linux tool dirs before Windows interop paths so Linux binaries
# always win over any Windows versions of the same tool (node, python, etc.)
export PATH="$HOME/.local/bin:$HOME/bin:/usr/local/bin:/usr/bin:/bin:$PATH"

# pyenv
export PYENV_ROOT="$HOME/.pyenv"
export PATH="$PYENV_ROOT/bin:$PATH"
if command -v pyenv &>/dev/null; then
  eval "$(pyenv init -)"
fi

# nvm
export NVM_DIR="$HOME/.nvm"
[[ -s "$NVM_DIR/nvm.sh" ]]            && source "$NVM_DIR/nvm.sh"
[[ -s "$NVM_DIR/bash_completion" ]]   && source "$NVM_DIR/bash_completion"

# ------------------------------------------------------------------------------
# WSL: ensure Linux tools take precedence over Windows equivalents
# ------------------------------------------------------------------------------
# Remove Windows node/npm/python from PATH to avoid cross-OS conflicts.
# nvm and pyenv (loaded above) provide the correct Linux binaries instead.
if [[ -n "${WSL_DISTRO_NAME:-}" ]]; then
  PATH="$(echo "$PATH" | tr ':' '\n' | grep -v '/mnt/c/' | tr '\n' ':' | sed 's/:$//')"
  export PATH
fi

# ------------------------------------------------------------------------------
# Load aliases
# ------------------------------------------------------------------------------
[[ -f "$HOME/.aliases" ]] && source "$HOME/.aliases"

# ------------------------------------------------------------------------------
# fzf — fuzzy finder key bindings and completion
# ------------------------------------------------------------------------------
[[ -f /usr/share/doc/fzf/examples/key-bindings.zsh ]]  && source /usr/share/doc/fzf/examples/key-bindings.zsh
[[ -f /usr/share/doc/fzf/examples/completion.zsh ]]     && source /usr/share/doc/fzf/examples/completion.zsh

# fzf use ripgrep as default command (much faster than find)
if command -v rg &>/dev/null; then
  export FZF_DEFAULT_COMMAND='rg --files --hidden --follow --glob "!.git"'
  export FZF_CTRL_T_COMMAND="$FZF_DEFAULT_COMMAND"
fi

# ------------------------------------------------------------------------------
# zsh-autosuggestions colours (subtle grey)
# ------------------------------------------------------------------------------
ZSH_AUTOSUGGEST_HIGHLIGHT_STYLE="fg=#6c6c6c"

# ------------------------------------------------------------------------------
# History
# ------------------------------------------------------------------------------
HISTSIZE=50000
SAVEHIST=50000
HISTFILE="$HOME/.zsh_history"
setopt HIST_IGNORE_DUPS
setopt HIST_IGNORE_SPACE
setopt SHARE_HISTORY

# ------------------------------------------------------------------------------
# Misc
# ------------------------------------------------------------------------------
# Make less more friendly for non-text input files
[[ -x /usr/bin/lesspipe ]] && eval "$(SHELL=/bin/sh lesspipe)"

# Editor
export EDITOR="vim"
export VISUAL="vim"

# ------------------------------------------------------------------------------
# Powerlevel10k config — generated by `p10k configure`, stored in .p10k.zsh
# ------------------------------------------------------------------------------
[[ -f "$HOME/.p10k.zsh" ]] && source "$HOME/.p10k.zsh"
